package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/printer"
	"go/types"
	"log"
	"os"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

const sdiTemplate = `
// Deps returns a list of dependencies required by {{.TypeName}}.
func (r *{{.TypeName}}) Deps() []any {
	return []any{
	{{- range .Deps}}
		(*{{.Typ}})(nil),
	{{- end}}
	}
}

// Inject sets the dependencies for {{.TypeName}}.
func (r *{{.TypeName}}) Inject(args []any) {
	for _, arg := range args {
		switch v := arg.(type) {
		{{- range .Deps}}
		case {{.Typ}}:
			r.{{.Name}} = v
		{{- end}}
		}
	}
}
`

type depInfo struct {
	Name string
	Typ  string
}

type structData struct {
	TypeName string
	Deps     []depInfo
}

func main() {
	if err := Run("."); err != nil {
		log.Fatalf("error: %v", err)
	}
}

func Run(dir string) error {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo,
		Dir:  dir,
	}

	pkgs, err := packages.Load(cfg, ".")
	if err != nil {
		return fmt.Errorf("failed to load packages: %w", err)
	}

	tmpl, err := template.New("sdi").Parse(sdiTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	for _, pkg := range pkgs {
		for _, file := range pkg.Syntax {
			filename := pkg.Fset.Position(file.Pos()).Filename

			if strings.HasSuffix(filename, "_sdi_gen.go") || strings.HasSuffix(filename, "_test.go") {
				continue
			}

			var buf bytes.Buffer
			hasDecls := false

			ast.Inspect(file, func(n ast.Node) bool {
				ts, ok := n.(*ast.TypeSpec)
				if !ok {
					return true
				}

				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					return true
				}

				var deps []depInfo
				for _, field := range st.Fields.List {
					if isInterface(pkg, field.Type) {
						typName := getTypeName(pkg, field.Type)
						for _, name := range field.Names {
							deps = append(deps, depInfo{Name: name.Name, Typ: typName})
						}
					}
				}

				if len(deps) > 0 {
					if !hasDecls {
						buf.WriteString(fmt.Sprintf("// Code generated by sdi. DO NOT EDIT.\npackage %s\n", pkg.Name))
						hasDecls = true
					}
					tmpl.Execute(&buf, structData{TypeName: ts.Name.Name, Deps: deps})
				}
				return true
			})

			if hasDecls {
				outputName := strings.TrimSuffix(filename, ".go") + "_sdi_gen.go"
				formatted, err := format.Source(buf.Bytes())
				if err != nil {
					log.Printf("failed to format %s: %v", outputName, err)
					continue
				}
				if err := os.WriteFile(outputName, formatted, 0644); err != nil {
					return fmt.Errorf("failed to write file %s: %w", outputName, err)
				}
				fmt.Printf("Generated: %s\n", outputName)
			}
		}
	}
	return nil
}

func isInterface(pkg *packages.Package, expr ast.Expr) bool {
	t := pkg.TypesInfo.TypeOf(expr)
	if t == nil {
		return false
	}
	_, ok := t.Underlying().(*types.Interface)
	return ok
}

func getTypeName(pkg *packages.Package, expr ast.Expr) string {
	var b bytes.Buffer
	printer.Fprint(&b, pkg.Fset, expr)
	return b.String()
}
