package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/printer"
	"go/types"
	"log"
	"os"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

const sdiTemplate = `
// Deps returns a list of dependencies required by {{.TypeName}}.
func (r *{{.TypeName}}{{.TypeParams}}) Deps() []any {
	return []any{
	{{- range .Deps}}
		(*{{.Typ}})(nil),
	{{- end}}
	}
}

// Inject sets the dependencies for {{.TypeName}}.
func (r *{{.TypeName}}{{.TypeParams}}) Inject(args []any) {
	for _, arg := range args {
		switch v := arg.(type) {
		{{- range .Deps}}
		case {{.Typ}}:
			r.{{.Name}} = v
		{{- end}}
		}
	}
}
`

type depInfo struct {
	Name string
	Typ  string
}

type structData struct {
	TypeName   string
	TypeParams string
	Deps       []depInfo
}

func main() {
	if err := Run("."); err != nil {
		log.Fatalf("error: %v", err)
	}
}

func Run(dir string) error {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo,
		Dir:  dir,
	}

	pkgs, err := packages.Load(cfg, ".")
	if err != nil {
		return fmt.Errorf("failed to load packages: %w", err)
	}

	tmpl, err := template.New("sdi").Parse(sdiTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	for _, pkg := range pkgs {
		depsFields := findDepsStructFields(pkg)
		if len(depsFields) == 0 {
			continue
		}

		for _, file := range pkg.Syntax {
			filename := pkg.Fset.Position(file.Pos()).Filename
			if skipFile(filename) {
				continue
			}

			var buf bytes.Buffer
			hasDecls := false

			ast.Inspect(file, func(n ast.Node) bool {
				ts, ok := n.(*ast.TypeSpec)
				if !ok || ts.Name.Name == "deps" {
					return true
				}

				st, ok := ts.Type.(*ast.StructType)
				if !ok || !structEmbedsDeps(st) {
					return true
				}

				if !hasDecls {
					buf.WriteString(fmt.Sprintf("// Code generated by sdi. DO NOT EDIT.\npackage %s\n", pkg.Name))
					hasDecls = true
				}

				if err := tmpl.Execute(&buf, structData{
					TypeName:   ts.Name.Name,
					TypeParams: typeParamsString(ts),
					Deps:       depsFields,
				}); err != nil {
					return true
				}
				return true
			})

			if hasDecls {
				outputName := strings.TrimSuffix(filename, ".go") + "_sdi_gen.go"
				if err := writeGenerated(outputName, buf.Bytes()); err != nil {
					return fmt.Errorf("failed to write file %s: %w", outputName, err)
				}
				fmt.Printf("Generated: %s\n", outputName)
			}
		}
	}
	return nil
}

func writeGenerated(outputName string, src []byte) error {
	formatted, err := format.Source(src)
	if err != nil {
		log.Printf("failed to format %s: %v", outputName, err)
		return os.WriteFile(outputName, src, 0644)
	}
	return os.WriteFile(outputName, formatted, 0644)
}

func skipFile(filename string) bool {
	return strings.HasSuffix(filename, "_sdi_gen.go") || strings.HasSuffix(filename, "_test.go")
}

// findDepsStructFields собирает interface-поля из type deps struct пакета.
func findDepsStructFields(pkg *packages.Package) []depInfo {
	var fields []depInfo

	for _, file := range pkg.Syntax {
		filename := pkg.Fset.Position(file.Pos()).Filename
		if skipFile(filename) {
			continue
		}

		ast.Inspect(file, func(n ast.Node) bool {
			ts, ok := n.(*ast.TypeSpec)
			if !ok || ts.Name.Name != "deps" {
				return true
			}

			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				return true
			}

			fields = append(fields, collectInterfaceFields(pkg, st)...)
			return true
		})
	}

	return fields
}

func collectInterfaceFields(pkg *packages.Package, st *ast.StructType) []depInfo {
	var deps []depInfo

	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			continue
		}
		if !isInterface(pkg, field.Type) {
			continue
		}

		typName := getTypeName(pkg, field.Type)
		for _, name := range field.Names {
			deps = append(deps, depInfo{Name: name.Name, Typ: typName})
		}
	}

	return deps
}

func structEmbedsDeps(st *ast.StructType) bool {
	for _, field := range st.Fields.List {
		if typeName(field.Type) == "deps" {
			return true
		}
	}
	return false
}

func typeName(expr ast.Expr) string {
	ident, ok := expr.(*ast.Ident)
	if !ok {
		return ""
	}
	return ident.Name
}

func typeParamsString(ts *ast.TypeSpec) string {
	if ts.TypeParams == nil {
		return ""
	}

	params := make([]string, 0)
	for _, field := range ts.TypeParams.List {
		for _, name := range field.Names {
			params = append(params, name.Name)
		}
	}
	return "[" + strings.Join(params, ", ") + "]"
}

func isInterface(pkg *packages.Package, expr ast.Expr) bool {
	t := pkg.TypesInfo.TypeOf(expr)
	if t == nil {
		return false
	}
	_, ok := t.Underlying().(*types.Interface)
	return ok
}

func getTypeName(pkg *packages.Package, expr ast.Expr) string {
	var b bytes.Buffer
	printer.Fprint(&b, pkg.Fset, expr)
	return b.String()
}
